apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops-news.fullname" (dict "root" . "component" "frontend-config") }}
  labels:
    {{- include "devops-news.labels" (dict "root" . "component" "frontend") | nindent 4 }}
data:
  nginx.conf: |
    {{- .Files.Get "config/nginx.conf" | replace "BACKEND_SERVICE" (include "devops-news.fullname" (dict "root" . "component" "backend")) | nindent 4 }}
