# Images Docker
images:
  repoAccount: "pueblo2708"
  pullPolicy: IfNotPresent
  tags:
    backend: "latest"
    frontend: "latest"
    cleaner: "latest"

# Backend (API Flask)
backend:
  replicas: 2
  logLevel: "INFO"
  service:
    type: ClusterIP
    port: 5000
  resources: {}
  extraEnv: []
  # Exemple d'utilisation :
  # extraEnv:
  #   - name: FEATURE_FLAG_X
  #     value: "true"
  #   - name: SENTRY_DSN
  #     value: "https://xxx@sentry.io/123"

# Frontend (Nginx)
frontend:
  replicas: 1
  service:
    type: LoadBalancer
    port: 80
  resources:
    limits:
      cpu: "200m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"

# Redis
redis:
  enabled: true
  password: "supersecret"
  storage: "1Gi"
  storageClassName: "standard-rwo"
  service:
    port: 6379

# Cleaner (CronJob)
cleaner:
  enabled: true
  schedule: "*/2 * * * *"
  maxAgeSeconds: 3600
